"""Generate the checked-in resource placement and relationship reference."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from gitopsctr.api import GVK, ApiKind
from gitopsctr.resource_model import (
    ResourceFamilyDefinition,
    ResourcePlane,
    ResourceRegistry,
    build_resource_registry,
)


def bundled_resource_registry() -> ResourceRegistry:
    """Build documentation from the explicit bundled API catalog, never ambient plugins."""

    from gitopsctr.artifacts import CONTAINER_IMAGES, FRONTEND_BUNDLE
    from gitopsctr.contrib.drivers.frontend_s3_cloudfront import API_KIND as FRONTEND_S3_CLOUDFRONT
    from gitopsctr.contrib.drivers.kubernetes_manifests import API_KIND as KUBERNETES_MANIFESTS
    from gitopsctr.contrib.drivers.oci_images import API_KIND as OCI_IMAGES
    from gitopsctr.contrib.drivers.terraform import API_KIND as TERRAFORM
    from gitopsctr.contrib.drivers.vite_oci_bundle import API_KIND as VITE_OCI_BUNDLE
    from gitopsctr.core_api import ENVIRONMENT, PROJECT, PROMOTION, RECEIPT, STACK, STACK_TEMPLATE

    bundled: tuple[ApiKind[object], ...] = (
        CONTAINER_IMAGES,
        FRONTEND_BUNDLE,
        ENVIRONMENT,
        PROJECT,
        PROMOTION,
        RECEIPT,
        STACK,
        STACK_TEMPLATE,
        FRONTEND_S3_CLOUDFRONT,
        KUBERNETES_MANIFESTS,
        OCI_IMAGES,
        TERRAFORM,
        VITE_OCI_BUNDLE,
    )
    catalog: dict[GVK, ApiKind[object]] = {}
    for api_kind in bundled:
        if api_kind.gvk in catalog:
            raise RuntimeError(f"duplicate bundled API kind: {api_kind.gvk}")
        catalog[api_kind.gvk] = api_kind
    return build_resource_registry(catalog)


def _placement_cell(family: ResourceFamilyDefinition, plane: ResourcePlane) -> str:
    placements = [placement for placement in family.placements if placement.plane == plane]
    if not placements:
        return "—"
    return "<br>".join(
        f"`{placement.scope}` · `{placement.collection}` · `{placement.contract_profile}`"
        + (" · default" if placement.default_for_inspection else "")
        for placement in placements
    )


def render_resource_model(registry: ResourceRegistry) -> str:
    """Render a deterministic public reference from the semantic registry."""

    lines = [
        "# Resource model",
        "",
        "<!-- Generated by `mise run resource-model`; do not edit by hand. -->",
        "",
        "This reference is generated from the same typed definitions used by resource inspection. A **plane** is an",
        "independent persisted representation; a relationship never implies that one resource is embedded in another.",
        "",
        "## Families and placements",
        "",
        "| Family | Selectors | Storage identity | Operator address | Installed API kinds | Source | Desired | Observed |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for family in sorted(registry.families, key=lambda item: item.name):
        selectors = ", ".join(f"`{selector}`" for selector in family.selectors)
        identity = family.identity.separator.join(segment.name for segment in family.identity.segments)
        filters = ", ".join(
            segment.filter_option for segment in family.identity.segments if segment.filter_option is not None
        )
        identity_cell = f"`{identity}`" + (f" ({filters})" if filters else "")
        gvks = "<br>".join(f"`{api_kind.gvk}`" for api_kind in registry.api_kinds_for_family(family.name))
        lines.append(
            f"| {family.name} | {selectors} | {identity_cell} | {family.addressing.documentation()} | {gvks} | "
            f"{_placement_cell(family, ResourcePlane.SOURCE)} | "
            f"{_placement_cell(family, ResourcePlane.DESIRED)} | "
            f"{_placement_cell(family, ResourcePlane.OBSERVED)} |"
        )

    lines.extend(
        [
            "",
            "Local identity plus placement drives collection discovery and duplicate detection. Each family's root, child, or",
            "mirror rule defines the qualified address that the CLI renders and accepts; the collection adapter encodes that",
            "same address into its canonical path while the document retains its local metadata.name. Environment and family",
            "remain separate command context. The repository adapter—not the controller or presentation layer—owns physical",
            "path discovery and encoding. `default` selects the persisted representation used by the family's inspection",
            "view; it does not make that representation authoritative for another plane.",
            "",
            "## Observation relationships",
            "",
            "| Relationship | Observer | Subject | Cardinality | Identity binding | Freshness binding |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for relationship in sorted(registry.observations, key=lambda item: item.name):
        documentation = relationship.binding.documentation()
        identity_binding = ", ".join(f"`{field}`" for field in documentation.identity_fields)
        freshness = f"`{documentation.freshness_field}` ↔ {documentation.freshness_target}"
        lines.append(
            f"| {relationship.name} | {relationship.observer_plane}/{relationship.observer_family} | "
            f"{relationship.subject_plane}/{relationship.subject_family} | {relationship.cardinality} | "
            f"{identity_binding} | {freshness} |"
        )

    lines.extend(
        [
            "",
            "A Receipt is therefore a separately stored observation of a desired Unit. A missing Receipt is allowed;",
            "matching `unitBlob` evidence is current, a different blob is stale, and more than one Receipt for the same",
            "subject violates the declared cardinality.",
            "",
            "## Artifact description relationships",
            "",
            "| Relationship | Describer | Artifact | Producer | Descriptor location | Verified bindings |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for relationship in sorted(registry.artifact_descriptions, key=lambda item: item.name):
        documentation = relationship.binding.documentation()
        verified = list(documentation.verified_bindings)
        verified[verified.index("producer")] = f"producer `{documentation.producer_field}`"
        bindings = ", ".join(verified[:-1]) + f", and {verified[-1]}"
        lines.append(
            f"| {relationship.name} | {relationship.describer_plane}/{relationship.describer_family} | "
            f"{relationship.artifact_plane}/{relationship.artifact_family} | "
            f"{relationship.producer_plane}/{relationship.producer_family} | "
            f"`{documentation.descriptor_field}` | {bindings} |"
        )

    lines.extend(
        [
            "",
            "Receipt artifact descriptors identify separately stored Artifact resources and bind their producer, media",
            "type, and serialized-byte digest. Artifact resources are not Receipt fields and are not Unit status.",
            "",
            "## Desired graph relationships",
            "",
            "| Relationship | Source | Target | Identity fence |",
            "| --- | --- | --- | --- |",
        ]
    )
    for relationship in sorted(registry.graph_relationships, key=lambda item: item.name):
        identity = ", ".join(f"`{field}`" for field in relationship.binding.documentation())
        lines.append(
            f"| {relationship.name} | {relationship.source_plane}/{relationship.source_family} | "
            f"{relationship.target_plane}/{relationship.target_family} | {identity} |"
        )
    lines.extend(
        [
            "",
            "Desired Stack relationships are registry contracts: a StackTemplate selection may be fenced by the",
            "template name, UID, and semantic content digest, while generated Units are fenced by the Stack owner UID.",
            "",
        ]
    )
    return "\n".join(lines)


def export_resource_model(destination: Path, *, check: bool) -> None:
    content = render_resource_model(bundled_resource_registry())
    existing = destination.read_text() if destination.is_file() else None
    if check:
        if existing != content:
            raise RuntimeError(f"generated resource model is stale: {destination}")
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("export",))
    parser.add_argument("destination", type=Path)
    parser.add_argument("--check", action="store_true", help="fail if the generated reference differs")
    args = parser.parse_args(argv)
    try:
        export_resource_model(args.destination, check=args.check)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
