"""Internal, dependency-clean resource API kernel."""

from gitopsctr.resource_api.api import GVK, ApiError, ApiKind, require_api_spec
from gitopsctr.resource_api.document import (
    ContractError,
    DocumentContract,
    JsonObject,
    JsonScalar,
    JsonValue,
    TypedDocumentContract,
    require_json_value,
)
from gitopsctr.resource_api.model import (
    ApiKindMembership,
    IdentityConstraint,
    IdentitySegmentDefinition,
    InspectionRecord,
    JsonFieldPath,
    LocalResourceIdentity,
    PersistedQualifiedNameAddressing,
    ResourceAddressing,
    ResourceAddressRuntime,
    ResourceApiError,
    ResourceApiFamily,
    ResourceIdentityDefinition,
    ResourceSelection,
    RootResourceAddressing,
    address_segments,
)
from gitopsctr.resource_api.registry import (
    ResourceApiContribution,
    ResourceApiRegistry,
    ResourceApiRelationship,
    build_resource_api_registry,
)

__all__ = [
    "GVK",
    "ApiError",
    "ApiKind",
    "ApiKindMembership",
    "ContractError",
    "DocumentContract",
    "IdentityConstraint",
    "IdentitySegmentDefinition",
    "InspectionRecord",
    "JsonFieldPath",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "LocalResourceIdentity",
    "PersistedQualifiedNameAddressing",
    "ResourceAddressRuntime",
    "ResourceAddressing",
    "ResourceApiContribution",
    "ResourceApiError",
    "ResourceApiFamily",
    "ResourceApiRegistry",
    "ResourceApiRelationship",
    "ResourceIdentityDefinition",
    "ResourceSelection",
    "RootResourceAddressing",
    "TypedDocumentContract",
    "address_segments",
    "build_resource_api_registry",
    "require_api_spec",
    "require_json_value",
]
