# yaml-language-server: $schema=https://niklasrosenstein.github.io/gitopsctr/schemas/apis/gitopsctr.io/v1/Stack/authored.schema.json
apiVersion: gitopsctr.io/v1
kind: Stack
metadata:
  name: application
spec:
  template:
    name: application
    source:
      fromPromotion:
        stack: application
  parameters:
    workload-name: gitopsctr-k8s-staging
    workload-resource: deployment/gitopsctr-k8s-staging
    message: promoted from dev to staging
    cluster-name: __CLUSTER_NAME__
    kube-context: __KUBE_CONTEXT__
    argocd-application: gitopsctr-k8s-staging
  units: [deploy]
  artifactImports:
    - unit: image
      name: containers
      apiVersion: artifact.gitopsctr.io/v1
      kind: ContainerImages
      fromPromotion:
        stack: application
