# yaml-language-server: $schema=https://niklasrosenstein.github.io/gitopsctr/schemas/apis/gitopsctr.io/v1/Stack/authored.schema.json
apiVersion: gitopsctr.io/v1
kind: Stack
metadata:
  name: preview
spec:
  template: application
  parameters:
    workload-name: gitopsctr-k8s-preview
    workload-resource: deployment/gitopsctr-k8s-preview
    message: unpartitioned preview
    cluster-name: __CLUSTER_NAME__
    kube-context: __KUBE_CONTEXT__
    argocd-application: gitopsctr-k8s-preview
  units: [image, deploy]
